#!/bin/sh
#
# ~/.config/sxiv/exec/key-handler
#

rotate() {
  degree="$1"
  tr '\n' '\0' | xargs -0 realpath | sort | uniq | while read file; do
  case "$(file -b -i "$file")" in
    image/jpeg*) jpegtran -rotate "$degree" -copy all -outfile "$file" "$file" ;;
    *)           mogrify  -rotate "$degree" "$file" ;;
  esac
done
}

while read file;
do
  case "$1" in
    "C-x")      xclip -in -filter | tr '\n' ' ' | xclip -in -selection clipboard ;;
    "C-c")      xclip -selection clipboard -target image/png "$file" ;;
    "C-e")      alacritty -e sh -c "exiv2 pr -q -pa '$file' | less" ;;
    "C-g")      gimp "$file" ;;
    "C-r")      rawtherapee "$file" ;;
    "C-w")      feh --bg-fill "$file" ;;
    "C-l")      cp -f "$file" "/home/colps/Pictures/lockimages/lock-image.jpg" ;;
    "C-i")      notify-send "File information" "$(mediainfo "$file")" ;;
    "C-comma")  rotate 270 ;;
    "C-period") rotate  90 ;;
    "C-slash")  rotate 180 ;;
  esac
done

