#!/bin/sh

#LAUNCHERS
$HOME/.config/bspwm/autostart.sh
#fix for moving spotify to specific workspace
bspc config external_rules_command ~/.config/bspwm/scripts/external_rules_command

#BSPWM configuration
#bspc config border_radius       8
bspc config border_width         2
bspc config window_gap           4
bspc config top_padding          25
bspc config bottom_padding       1
bspc config left_padding         1
bspc config right_padding        1
bspc config single_monocle       false
#bspc config click_to_focus       true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config focus_by_distance    true
bspc config focus_follows_pointer true
#bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#BSPWM coloring
bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	"#5e81ac"
bspc config presel_feedback_color	"#5e81ac"
#bspc config urgent_border_color 	"#dd2727"

#Single monitor
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

#Dual monitor
#bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9
#bspc monitor HDMI-1 -d 10

#Fullscreen applications
#bspc rule -a Gimp state=fullscreen

#Floating applications
bspc rule -a Arandr state=floating
bspc rule -a Galculator state=floating
bspc rule -a Pavucontrol state=floating sticky=on
bspc rule -a rofi state=floating sticky=on
bspc rule -a 'QML Timer' state=floating sticky=on

#Tiled applications
bspc rule -a Zathura state=tiled

#open applications on specific workspaces
# dev
bspc rule -a Luakit desktop='^4'
# Office
bspc rule -a Joplin desktop='^3'
bspc rule -a Todoist desktop='^3'
bspc rule -a google-chrome desktop='^3'
bspc rule -a libreoffice-startcenter desktop='^3'
# messages
bspc rule -a Skype desktop='^9'
bspc rule -a discord desktop='^9'
bspc rule -a TelegramDesktop desktop='^9'
bspc rule -a Rambox desktop='^9'
bspc rule -a zoom desktop='^9'
bspc rule -a 'Microsoft Teams - Preview' desktop='^9'
# images
bspc rule -a Gimp desktop='^5'
bspc rule -a Ristretto desktop='^5'
bspc rule -a Dia desktop='^5'
bspc rule -a Inkscape desktop='^5'
bspc rule -a XMind desktop='^5'
# video
bspc rule -a Stremio desktop='^10'
# arcolinux
bspc rule -a Arcolinux-tweak-tool.py desktop='^7' follow=on
bspc rule -a Arcolinux-welcome-app.py desktop='^7' follow=on
bspc rule -a Arcolinux-calamares-tool.py desktop='^7' follow=on
# music
bspc rule -a Audacious desktop='^6'
bspc rule -a Picard desktop='^6'
bspc rule -a 'YouTube to MP3' desktop='^6'
# spotify fix
sleep 1
wmctrl -r spotify -t 6
exit

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_eDP1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI1)

###External rules
##Pseudo automatic mode: always splits focused window when opening new window
#bspc config external_rules_command ~/.config/bspwm/scripts/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command ~/.config/bspwm/scripts/adjust-new-window

