#!/bin/sh

#LAUNCHERS
$HOME/.config/bspwm/autostart.sh
#fix for moving spotify to specific workspace
bspc config external_rules_command ~/.config/bspwm/scripts/external_rules_command

#BSPWM configuration
#bspc config border_radius       8
bspc config border_width         2
bspc config window_gap           4
bspc config top_padding          20
bspc config bottom_padding       1
bspc config left_padding         1
bspc config right_padding        1
bspc config single_monocle       false
#bspc config click_to_focus       true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config focus_by_distance    true
bspc config focus_follows_pointer true
#bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#BSPWM coloring
bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	"#5e81ac"
bspc config presel_feedback_color	"#5e81ac"
#bspc config urgent_border_color 	"#dd2727"


#Single monitor
#bspc monitor -d 1 2 3 4 5 6 7 8 9 10

#Dual monitor
bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9
bspc monitor HDMI1 -d 10

#Fullscreen applications
#bspc rule -a Gimp state=fullscreen

#Floating applications
bspc rule -a Arandr state=floating
bspc rule -a Galculator state=floating
bspc rule -a Pavucontrol state=floating sticky=on
bspc rule -a rofi state=floating sticky=on
bspc rule -a 'QML Timer' state=floating sticky=on

#Tiled applications
#bspc rule -a Gnome-disks state=tiled
bspc rule -a Surf state=tiled

#open applications on specific workspaces
bspc rule -a Skype desktop='^9'
bspc rule -a discord desktop='^9'
bspc rule -a TelegramDesktop desktop='^9'
bspc rule -a Audacious desktop='^6'
bspc rule -a Gimp-2.10 desktop='^5'
bspc rule -a Mirage desktop='^5'
bspc rule -a Dia deskt:op='^6'
bspc rule -a Inkscape desktop='^6'
bspc rule -a Arcolinux-tweak-tool.py desktop='^7' follow=on
bspc rule -a Arcolinux-welcome-app.py desktop='^7' follow=on
bspc rule -a Arcolinux-calamares-tool.py desktop='^7' follow=on
#Spotify fix
sleep 1
wmctrl -r spotify -t 6
exit

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_eDP1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI1)

###External rules
##Pseudo automatic mode: always splits focused window when opening new window
#bspc config external_rules_command ~/.config/bspwm/scripts/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command ~/.config/bspwm/scripts/adjust-new-window
