#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X
# bspc monitor eDP-1      -d II III IV V VI VII VIII IX 
# bspc monitor DVI-I-1-1  -d I
# bspc monitor HDMI-1     -d X

bspc config border_width            2
bspc config window_gap              5

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config pointer_follows_focus   true
bspc config focus_follows_pointer   true

bspc rule -a rambox         desktop='^0'
bspc rule -a firefox        desktop='^2'
bspc rule -a gimp-2.10      desktop='^7' 
bspc rule -a tidal-hifi     desktop='^8' 

# miscellaneous
bspc rule -a Kupfer.py      focus=on
bspc rule -a Screenkey      manage=off

# floating
bspc rule -a gnome-calculator state=floating
bspc rule -a zoom             state=floating
bspc rule -a discord          state=floating
bspc rule -a mplayer2         state=floating
bspc rule -a Yad              state=floating

# Border
bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

#
# Autostart
#

# Set display from arandr saved script
sh ~/.screenlayout/three_monitors.sh &
#
# Bar
~/.config/polybar/launch.sh &
#
# Notifications
/usr/bin/dunst &
#
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
#
# Wallpaper
nitrogen --restore &
#
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &
#
# Picom
pkill picom
picom -b &
#
# Network Applet
nm-applet --indicator &
#
# Cursor
xsetroot -cursor_name left_ptr &
xset r rate 300 50
#
# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh
#
# apps
rambox &

